<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    $cssCode .= <<<CSS

input[type="text"]::placeholder,
input[type="email"]::placeholder,
input[type="url"]::placeholder,
input[type="password"]::placeholder,
input[type="search"]::placeholder,
input[type="number"]::placeholder,
input[type="tel"]::placeholder,
input[type="range"]::placeholder,
input[type="date"]::placeholder,
input[type="month"]::placeholder,
input[type="week"]::placeholder,
input[type="time"]::placeholder,
input[type="datetime"]::placeholder,
input[type="datetime-local"]::placeholder,
input[type="color"]::placeholder,
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea::placeholder,
textarea,
a,
.mainmenu-container ul ul .menu-item > a,
.mainmenu-container li a span,
.entry-meta a:not(:hover),
.c-body,
.comment-form label,
.comment-form a,
.opal-custom-menu-inline .widget_nav_menu li ul a,
.cart-collaterals .cart_totals th,
#payment .payment_methods li.woocommerce-notice,
#payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods li.woocommerce-info,
table.woocommerce-checkout-review-order-table th,
.single-product div.product .product_meta .sku_wrapper span,
.single-product div.product .product_meta .sku_wrapper a,
.single-product div.product .product_meta .posted_in span,
.single-product div.product .product_meta .posted_in a,
.single-product div.product .product_meta .tagged_as span,
.single-product div.product .product_meta .tagged_as a,
.opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit span:before,
.mc4wp-form .widget-title p .c-body,
.mc4wp-form .widget-title p .comment-form label,
.comment-form .mc4wp-form .widget-title p label,
.mc4wp-form .widget-title p .comment-form a,
.comment-form .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .opal-custom-menu-inline .widget_nav_menu li ul a,
.opal-custom-menu-inline .widget_nav_menu li ul .mc4wp-form .widget-title p a,
.mc4wp-form .widget-title p .cart-collaterals .cart_totals th,
.cart-collaterals .cart_totals .mc4wp-form .widget-title p th,
.mc4wp-form .widget-title p table.woocommerce-checkout-review-order-table th,
table.woocommerce-checkout-review-order-table .mc4wp-form .widget-title p th,
.woocommerce-shipping-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.woocommerce-billing-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.opal-currency_switcher .list-currency button[type="submit"],
ul.products li.product .price del,
.select-items div,
.single-product table.group_table .woocommerce-grouped-product-list-item__price del .amount,
.widget .woof_list_label li .woof_label_term,
.woocommerce-widget-layered-nav .osf-color-type .color-count {
  color: {$color_body}; }



h1,
h2,
h3,
h4,
h5,
h6,
.h1,
.h2,
.h3,
.custom-title,
.entry-header .entry-title,
.related-posts .related-heading,
.comments-title,
.comment-respond .comment-reply-title,
.h4,
.cat-tags-links .tags-heading,
.column-item .entry-title,
.woocommerce-MyAccount-content h2,
.h5,
h2.widget-title,
h2.widgettitle,
.h6,
.widget_rss li .rsswidget,
.entry-meta a.url:not(:hover),
.entry-content blockquote cite a,
.entry-content strong,
.entry-content dt,
.entry-content th,
.entry-content dt a,
.entry-content th a,
.single .navigation .nav-link a,
.comment-content strong,
.comment-author,
.comment-author a,
.comment-metadata a.comment-edit-link,
.comment-content table th,
.comment-content table td a,
.comment-content dt,
.c-heading,
fieldset legend,
.vertical-navigation .menu-open-label,
.author-wrapper .author-name,
.page .entry-header .entry-title,
table.shop_table_responsive tbody th,
.filter-close,
table.cart:not(.wishlist_table) th,
table.cart:not(.wishlist_table) .product-name a,
.cart-collaterals .cart_totals .order-total .woocommerce-Price-amount,
.cart-collaterals .cart_totals .amount,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info,
#payment .payment_methods > .wc_payment_method > label,
table.woocommerce-checkout-review-order-table .order-total .woocommerce-Price-amount,
table.woocommerce-checkout-review-order-table .product-name,
.woocommerce-billing-fields label,
.woocommerce-billing-fields > h3,
.cart th,
.shop_table th,
.woocommerce-account .woocommerce-MyAccount-content strong,
.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Price-amount,
.osf-sorting .display-mode button.active,
.osf-sorting .display-mode button:hover,
.woocommerce-Tabs-panel table.shop_attributes th,
#osf-accordion-container table.shop_attributes th,
.single-product div.product .product_meta .sku_wrapper,
.single-product div.product .product_meta .posted_in,
.single-product div.product .product_meta .tagged_as,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control],
.widget .woof_list_checkbox input[type="checkbox"] + label:after,
.widget .woof_list_checkbox input[type="checkbox"]:checked + label,
.widget .woof_list_radio input[type="radio"]:checked + label,
.woosw-list table.woosw-content-items .woosw-content-item .woosw-content-item--add p > a,
.woosw-area .woosw-inner .woosw-content .woosw-content-mid table.woosw-content-items .woosw-content-item .woosw-content-item--add p > a,
.tribe-events-list .tribe-events-list-event-title a,
.elementor-featured-box-wrapper .elementor-featured-box-title,
.woocommerce-tabs ul.tabs li a,
.single-product table.group_table .woocommerce-grouped-product-list-item__label label a,
.osf-active-filters .osf_active_filters_label,
.product_list_widget li .product-title a,
.woocommerce-product-list li .product-title a,
.product-style-1 li.product h2 a,
.product-style-1 li.product h3 a,
.product-style-1 li.product .woocommerce-loop-product__title a {
  color: {$color_heading}; }



blockquote:before,
.main-navigation .top-menu > li:not(:last-child):before,
.main-navigation .top-menu > li > a:hover,
.main-navigation .top-menu > li.current-menu-item > a,
.mainmenu-container li.current-menu-parent > a,
.mainmenu-container .menu-item > a:hover,
.page-numbers:not(ul):hover,
.page-numbers.current:not(ul),
.cat-links a,
.entry-meta .entry-meta-inner > span:not(:first-child):before,
.entry-meta .cat-links a,
.pbr-social-share a:hover,
.single .navigation > div:hover,
.single .navigation > div:hover .nav-title,
.single .navigation > div:hover a,
.single .navigation > div:hover b,
.single .navigation .nav-title,
.error404 .error-404-bkg,
.error404 .sub-h2-1,
.site-header-account > a span,
.comment-author a:hover,
.comment-metadata a.comment-edit-link:hover,
.comment-metadata a:hover,
.comment-reply-link,
.widget_rss li .rsswidget:hover,
.button-outline-primary,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.widget_shopping_cart .buttons .button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button,
.c-primary,
.main-navigation .menu-item > a:hover,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.entry-header .entry-title a:hover,
.entry-content blockquote cite a:hover,
.site-header-account .account-links-menu li a:hover,
.site-header-account .account-dashboard li a:hover,
.comment-form a:hover,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.opal-custom-menu-inline .widget ul li a:hover,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-nav-menu-popup .mfp-close,
.site-header-cart .widget_shopping_cart .product_list_widget li a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:focus,
.site-header-cart .shopping_cart_nav .product_list_widget li a:hover,
.site-header-cart .shopping_cart_nav .product_list_widget li a:focus,
.site-header-cart .woocommerce-mini-cart__empty-message:before,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a:hover,
.woocommerce-privacy-policy-link,
.opal-currency_switcher .list-currency button[type="submit"]:hover,
.opal-currency_switcher .list-currency li.active button[type="submit"],
ul.products li.product.osf-product-list .price,
ul.products li.product .posfed_in a:hover,
.select-items div:hover,
.button-wrapper #chart-button,
.product_list_widget li .product-title a:hover,
.product_list_widget li .product-title a:active,
.product_list_widget li .product-title a:focus,
.woocommerce-product-list li .product-title a:hover,
.woocommerce-product-list li .product-title a:active,
.woocommerce-product-list li .product-title a:focus,
.product_list_widget a:hover,
.product_list_widget a:active,
.product_list_widget a:focus,
.woocommerce-product-list a:hover,
.woocommerce-product-list a:active,
.woocommerce-product-list a:focus,
.tribe-events-list .tribe-events-list-event-title a:hover,
.tribe-events-list .tribe-event-schedule-details,
.tribe-events-list .time-details,
#secondary .elementor-widget-wp-widget-recent-posts a,
.elementor-widget-opal-box-overview .elementor-box-overview-wrapper .entry-header a,
.contactform-content .form-title,
.tribe-events-inner .tribe-events-list-event-title a:hover,
.tribe-events-inner .tribe-events-event-meta .tribe-event-schedule-details,
.elementor-widget-heading .sub-title i,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu > .menu-item:before,
.elementor-widget-opal-price-table .elementor-price-table__feature-inner .opal-icon-times,
.elementor-widget-scroll-timeline .st-year,
.elementor-video-popup:hover .elementor-video-title,
.elementor-video-popup:hover .elementor-video-icon,
.site-header-cart .widget_shopping_cart p.total .woocommerce-Price-amount,
.site-header-cart .shopping_cart_nav p.total .woocommerce-Price-amount,
.header-button .count,
.header-button:hover,
.header-button:focus,
table.cart:not(.wishlist_table) .product-subtotal .woocommerce-Price-amount,
.woocommerce-MyAccount-navigation ul li.is-active a,
li.product .posted_in a:hover,
ul.products li.product .price,
.single-product div.product .summary .yith-wcwl-add-to-wishlist > div > a:hover:before,
.single-product div.product .summary .compare:hover:before,
.single-product div.product .summary .price,
.single-product table.group_table .woocommerce-grouped-product-list-item__label label a:hover,
.single-product table.group_table .woocommerce-grouped-product-list-item__price .amount,
.single-product table.group_table .woocommerce-grouped-product-list-item__price ins,
.single-product .woocommerce-tabs .wc-tabs .active a,
.single-product div.product .entry-summary .onsale,
.product_list_widget .amount,
.woocommerce-product-list .amount,
.product_list_widget ins .amount,
.woocommerce-product-list ins .amount,
.product_list_widget del .amount,
.woocommerce-product-list del .amount,
.widget_price_filter .price_label .from,
.widget_price_filter .price_label .to,
.single-product div.product .entry-summary .woosc-btn:hover,
.single-product div.product .entry-summary .wooscp-btn:hover,
.single-product div.product .entry-summary .woosw-btn:hover,
.tribe-events-list-separator-month,
.single-tribe_events #tribe-events-content .tribe-events-event-meta dd.tribe-venue,
.single-tribe_events #tribe-events-content .tribe-events-event-meta dd.tribe-venue-location,
.single-tribe_events #tribe-events-content .tribe-events-event-meta dd.tribe-organizer,
.tribe-events-tooltip .tribe-event-duration,
.album-post-thumbnail .entry-title a:hover {
  color: {$color_primary->toCss()}; }


.f-primary {
  fill: {$color_primary->toCss()}; }


::selection,
.comments-link span,
.entry-header .entry-date a,
.cat-tags-links .tags-links a:hover,
.cat-tags-links .tags-links a:focus,
body.blog article .post-content:after,
.error404 .return-home:hover,
#secondary .widget:after,
.widget_archive ul li a:before,
.widget_nav_menu ul li a:before,
.widget_categories ul li a:before,
.widget_pages ul li a:before,
.widget_meta ul li a:before,
.widget_product_categories ul li a:before,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.wp_widget_tag_cloud a:hover:before,
.wp_widget_tag_cloud a:focus:before,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.error404 .go-back,
.scrollup,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.elementor-widget-opal-single-product .button,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.tribe-events-button,
#tribe-events .tribe-events-button,
#tribe-bar-form .tribe-bar-submit input[type=submit],
.button-default:hover,
.button-default:active,
.button-default:focus,
.button-dark:hover,
.more-link:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
table.cart:not(.wishlist_table) td.actions button:hover[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:hover,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:hover,
.button-dark:active,
.more-link:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
table.cart:not(.wishlist_table) td.actions button:active[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:active,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:active,
.button-dark:focus,
.more-link:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
table.cart:not(.wishlist_table) td.actions button:focus[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:focus,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.bg-primary,
[class*="after-title"]:after,
.before-title-primary:before,
.img-animated .elementor-image:after,
.col-animated:after,
.elementor-counter-divider span,
.elementor-widget-divider .elementor-divider-separator:before,
.tribe-events-inner .tribe-events-event-meta .tribe-event-schedule-details:after,
.elementor-view-framed .elementor-icon,
.column-item .entry-category a,
.column-item.post-style-2 .post-inner:after,
.opal-timeline .timeline-line,
.elementor-post-timeline .timeline-line,
.opal-timeline .column-item .timeline-item-line,
.elementor-post-timeline .column-item .timeline-item-line,
.opal-timeline .column-item:after,
.elementor-post-timeline .column-item:after,
.elementor-widget-opal-product-categories .cats-title a:after,
.scroll-timeline-nav ul span:after,
.elementor-team-meta-inner:hover .elementor-team-image,
.notification-added-to-cart .ns-content,
#payment .place-order .button:hover,
form.track_order p:last-of-type button[type="submit"]:hover,
form.track_order p:last-of-type button[type="submit"]:focus,
.shop-action .yith-wcqv-button:hover,
.shop-action .yith-wcwl-add-to-wishlist > div > a:hover,
.shop-action .compare:hover,
.shop-action a[class*="product_type_"]:hover,
.shop-action a.loading[class*="product_type_"],
.woocommerce-tabs ul.tabs li a:after,
.widget_price_filter .ui-slider .ui-slider-handle,
.widget_price_filter .ui-slider .ui-slider-range,
.handheld-footer-bar .cart .footer-cart-contents .count,
.shop-action .woosq-btn:hover,
.shop-action .wooscp-btn:hover,
.shop-action .woosc-btn:hover,
.shop-action .woosw-btn:hover,
ul.tribe-events-sub-nav a:hover,
.tribe-events-back a:hover,
.tribe-events-list-widget .tribe-events-widget-link a:hover,
.tribe-events-adv-list-widget .tribe-events-widget-link a:hover,
.tribe-events-list .tribe-event-schedule-details:after,
.tribe-events-list .time-details:after,
.tribe-events-calendar td .opal-inner:hover,
.tribe-events-calendar td.tribe-events-present div[id*='tribe-events-daynum-'],
.tribe-events-calendar td.tribe-events-present div[id*='tribe-events-daynum-'] > a,
.video-post-thumbnail:after,
.album-post-thumbnail:after {
  background-color: {$color_primary->toCss()}; }



.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.error404 .go-back,
.scrollup,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.elementor-widget-opal-single-product .button,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.tribe-events-button,
#tribe-events .tribe-events-button,
#tribe-bar-form .tribe-bar-submit input[type=submit],
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.form-control:focus,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
.prev.page-numbers:hover,
.next.page-numbers:hover,
.cat-tags-links .tags-links a:hover,
.cat-tags-links .tags-links a:focus,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.wp_widget_tag_cloud a:hover:after,
.wp_widget_tag_cloud a:focus:after,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
.button-default:hover,
.button-default:active,
.button-default:focus,
.button-dark:hover,
.more-link:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
table.cart:not(.wishlist_table) td.actions button:hover[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:hover,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:hover,
.button-dark:active,
.more-link:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
table.cart:not(.wishlist_table) td.actions button:active[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:active,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:active,
.button-dark:focus,
.more-link:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
table.cart:not(.wishlist_table) td.actions button:focus[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:focus,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.widget_shopping_cart .buttons .button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button,
.button-outline-primary:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-outline-primary:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-outline-primary.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-outline-primary.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.b-primary,
.elementor-nav-menu--main .elementor-nav-menu ul,
.elementor-video-popup:hover .elementor-video-icon,
#payment .place-order .button:hover,
form.track_order p:last-of-type button[type="submit"]:hover,
form.track_order p:last-of-type button[type="submit"]:focus,
form.track_order p input[type="text"]:hover,
form.track_order p input[type="text"]:focus,
.single-product div.product .summary .yith-wcwl-add-to-wishlist > div > a:hover,
.single-product div.product .summary .compare:hover,
.osf-product-deal .woocommerce-product-list .opal-countdown .day,
.otf-product-recently-content li:hover .product-thumbnail img,
.single-product div.product .entry-summary .woosc-btn:hover,
.single-product div.product .entry-summary .wooscp-btn:hover,
.single-product div.product .entry-summary .woosw-btn:hover,
#tribe-bar-form input[type='text']:focus {
  border-color: {$color_primary->toCss()}; }


#tribe-bar-views-toggle:after,
#tribe-bar-collapse-toggle span.tribe-bar-toggle-arrow::after {
  border-top-color: {$color_primary->toCss()}; }


.tribe-bar-views-open #tribe-bar-views-toggle:after,
#tribe-bar-collapse-toggle.tribe-bar-filters-open span.tribe-bar-toggle-arrow::after {
  border-bottom-color: {$color_primary->toCss()}; }



.btn-link:focus,
.elementor-element .elementor-button-link .elementor-button:focus,
.btn-link:hover,
.elementor-element .elementor-button-link .elementor-button:hover,
.button-link:focus,
.button-link:hover,
a:hover,
a:active,
.cat-links a:hover,
.entry-meta .cat-links a:hover {
  color: {$color_primary_hover->toCss()}; }


.entry-header .entry-date a:hover,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.error404 .go-back:hover,
.scrollup:hover,
.comment-form .form-submit input:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.elementor-widget-opal-single-product .button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.tribe-events-button:hover,
#tribe-events .tribe-events-button:hover,
#tribe-bar-form .tribe-bar-submit input:hover[type=submit],
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.error404 .go-back:active,
.scrollup:active,
.comment-form .form-submit input:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.elementor-widget-opal-single-product .button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.tribe-events-button:active,
#tribe-events .tribe-events-button:active,
#tribe-bar-form .tribe-bar-submit input:active[type=submit],
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.error404 .active.go-back,
.active.scrollup,
.comment-form .form-submit input.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.elementor-widget-opal-single-product .active.button,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.active.tribe-events-button,
#tribe-events .active.tribe-events-button,
#tribe-bar-form .tribe-bar-submit input.active[type=submit],
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.error404 .show > .dropdown-toggle.go-back,
.show > .dropdown-toggle.scrollup,
.comment-form .form-submit .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.elementor-widget-opal-single-product .show > .dropdown-toggle.button,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.show > .dropdown-toggle.tribe-events-button,
#tribe-events .show > .dropdown-toggle.tribe-events-button,
#tribe-bar-form .tribe-bar-submit .show > input.dropdown-toggle[type=submit],
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.column-item .entry-category a:hover {
  background-color: {$color_primary_hover->toCss()}; }


.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.error404 .go-back:active,
.scrollup:active,
.comment-form .form-submit input:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.elementor-widget-opal-single-product .button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.tribe-events-button:active,
#tribe-events .tribe-events-button:active,
#tribe-bar-form .tribe-bar-submit input:active[type=submit],
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.error404 .active.go-back,
.active.scrollup,
.comment-form .form-submit input.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.elementor-widget-opal-single-product .active.button,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.active.tribe-events-button,
#tribe-events .active.tribe-events-button,
#tribe-bar-form .tribe-bar-submit input.active[type=submit],
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.error404 .show > .dropdown-toggle.go-back,
.show > .dropdown-toggle.scrollup,
.comment-form .form-submit .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.elementor-widget-opal-single-product .show > .dropdown-toggle.button,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.show > .dropdown-toggle.tribe-events-button,
#tribe-events .show > .dropdown-toggle.tribe-events-button,
#tribe-bar-form .tribe-bar-submit .show > input.dropdown-toggle[type=submit],
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.error404 .go-back:hover,
.scrollup:hover,
.comment-form .form-submit input:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.elementor-widget-opal-single-product .button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.tribe-events-button:hover,
#tribe-events .tribe-events-button:hover,
#tribe-bar-form .tribe-bar-submit input:hover[type=submit],
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
  border-color: {$color_primary_hover->toCss()}; }



.error404 .sub-h2-2,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.elementor-element .elementor-button-outline_secondary .elementor-button,
.c-secondary,
.author-wrapper .author-name h6,
.list-feature-box > li:before,
.elementor-widget-opal-box-overview .elementor-box-overview-wrapper .entry-header a:hover,
.contactform-content button.mfp-close {
  color: {$color_secondary->toCss()}; }



.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.mailchimp-button-outline_secondary button:hover,
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.mailchimp-button-outline_secondary button:active,
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.mailchimp-button-outline_secondary button.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.bg-secondary,
.before-title-secondary:before,
#secondary .elementor-widget-wp-widget-categories a:before,
.elementor-accordion .elementor-tab-title.elementor-active .elementor-accordion-icon,
#secondary .elementor-nav-menu a:before,
.e--pointer-dot a:before {
  background-color: {$color_secondary->toCss()}; }



.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.elementor-element .elementor-button-outline_secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.b-secondary {
  border-color: {$color_secondary->toCss()}; }



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-default-content-layout-2cr #content .wrap,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.opal-archive-style-4.blog .site-main,
.opal-archive-style-4.archive .site-main,
.site-footer .widget-area,
.comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
.list-feature-box,
[data-elementor-columns],
.opal-canvas-filter.top .opal-canvas-filter-wrap,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone,
.woocommerce-cart .woocommerce,
.woocommerce-billing-fields .woocommerce-billing-fields__field-wrapper,
.woocommerce-MyAccount-content form[class^="woocommerce-"],
.woocommerce-columns--addresses,
.woocommerce-account .entry-content > .woocommerce,
.woocommerce-account .entry-content > .woocommerce .u-columns.woocommerce-Addresses,
.woocommerce-Addresses,
.woocommerce-address-fields__field-wrapper,
ul.products,
.osf-sorting,
.single-product div.product {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.col-4,
[data-elementor-columns-mobile="3"] .column-item,
.col-5,
.col-6,
[data-elementor-columns-mobile="2"] .column-item,
.single-product.opal-comment-form-2 .comment-form-author,
.single-product.opal-comment-form-2 .comment-form-email,
.col-7,
.col-8,
.col-9,
.col-10,
.opal-timeline .column-item,
.elementor-post-timeline .column-item,
.col-11,
.col-12,
.related-posts .column-item,
.opal-default-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
.site-footer .widget-area .widget-column,
.comment-form > p,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.woocommerce-cart .cart-empty,
.woocommerce-cart .return-to-shop,
.woocommerce-cart .woocommerce-notices-wrapper,
.woocommerce-billing-fields .form-row-wide,
.woocommerce-MyAccount-content form[class^="woocommerce-"] > *:not(fieldset),
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-wide,
#customer_details [class*='col'],
.columns-1 ul.products li.product,
.columns-1 ul.products > li,
#reviews .comment-form-rating,
.single-product .woocommerce-tabs,
.col,
body #secondary,
.opal-canvas-filter.top .opal-canvas-filter-wrap section,
.opal-canvas-filter.top .opal-canvas-filter-wrap section.WOOF_Widget .woof_redraw_zone .woof_container,
.columns-5 ul.products li.product,
.columns-5 ul.products > li,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.columns-6 ul.products li.product,
.columns-6 ul.products > li,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.opal-archive-style-1 .column-item,
.opal-archive-style-2 .column-item,
.opal-archive-style-3 .column-item,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.list-feature-box > li,
.woocommerce-billing-fields .form-row-first,
.woocommerce-billing-fields .form-row-last,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-first,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-last,
ul.products li.product,
.columns-2 ul.products li.product,
.columns-2 ul.products > li,
.columns-3 ul.products li.product,
.columns-3 ul.products > li,
.columns-4 ul.products li.product,
.columns-4 ul.products > li,
.opal-content-layout-2cl .columns-3 ul.products li.product,
.opal-content-layout-2cl .columns-3 ul.products > li,
.opal-content-layout-2cr .columns-3 ul.products li.product,
.opal-content-layout-2cr .columns-3 ul.products > li,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.opal-archive-style-1.opal-content-layout-2cr .column-item,
.opal-archive-style-2.opal-content-layout-2cr .column-item,
.opal-archive-style-3.opal-content-layout-2cr .column-item,
.cart-collaterals .cross-sells,
.woocommerce-columns--addresses .woocommerce-column,
.woocommerce-account .entry-content > .woocommerce .u-columns [class^="u-column"],
.woocommerce-account .woocommerce-ResetPassword,
.woocommerce-address-fields__field-wrapper .form-row,
.woocommerce-product-carousel ul.products li.product,
.osf-sorting .woocommerce-message,
.osf-sorting .woocommerce-notice,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group,
.single-product div.product .images,
.single-product div.product .entry-summary,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.col-md-4,
.comment-form .comment-form-url,
.comment-form .comment-form-email,
.comment-form .comment-form-author,
[data-elementor-columns-tablet="3"] .column-item,
.col-md-5,
.osf-sorting .osf-sorting-group,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.col-md-7,
.osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.cart-collaterals,
.woocommerce-account .woocommerce-MyAccount-navigation,
.woocommerce-account .woocommerce-MyAccount-content,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
[data-elementor-columns="6"] .column-item,
.col-lg-3,
[data-elementor-columns="4"] .column-item,
.col-lg-4,
[data-elementor-columns="3"] .column-item,
.col-lg-5,
.col-lg-6,
[data-elementor-columns="2"] .column-item,
.col-lg-7,
.col-lg-8,
.woocommerce-cart .woocommerce-cart-form,
.opal-content-layout-2cl .osf-sorting .osf-sorting-group + .osf-sorting-group,
.opal-content-layout-2cr .osf-sorting .osf-sorting-group + .osf-sorting-group,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
[data-elementor-columns="1"] .column-item,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
ul.elementor-nav-menu--dropdown.mega-fullwidth > li.mega-menu-item > .elementor,
.opal-canvas-filter.top,
.single-product .related.products,
.single-product .up-sells.products,
.otf-product-recently-content .widget_recently_viewed_products {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-fullwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-fullwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-fullwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-fullwidth > li.mega-menu-item > .elementor, .opal-canvas-filter.top, .single-product .related.products,
    .single-product .up-sells.products, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 1140px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $border_radius, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.error404 .go-back,
.scrollup,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.elementor-widget-opal-single-product .button,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.tribe-events-button,
#tribe-events .tribe-events-button,
#tribe-bar-form .tribe-bar-submit input[type=submit],
.button-default:hover,
.button-default:active,
.button-default:focus,
.button-dark:hover,
.more-link:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
table.cart:not(.wishlist_table) td.actions button:hover[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:hover,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:hover,
.button-dark:active,
.more-link:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
table.cart:not(.wishlist_table) td.actions button:active[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:active,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:active,
.button-dark:focus,
.more-link:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
table.cart:not(.wishlist_table) td.actions button:focus[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical:focus,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical:focus,
.elementor-element .elementor-button-primary .elementor-button {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.page .edit-link a.post-edit-link:hover,
.error404 .go-back:hover,
.scrollup:hover,
.comment-form .form-submit input:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.elementor-widget-opal-single-product .button:hover,
.wc-proceed-to-checkout .button:hover,
.woocommerce-cart .return-to-shop a:hover,
.wishlist_table .product-add-to-cart a.button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.tribe-events-button:hover,
#tribe-events .tribe-events-button:hover,
#tribe-bar-form .tribe-bar-submit input:hover[type=submit],
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.page .edit-link a.post-edit-link:active,
.error404 .go-back:active,
.scrollup:active,
.comment-form .form-submit input:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.elementor-widget-opal-single-product .button:active,
.wc-proceed-to-checkout .button:active,
.woocommerce-cart .return-to-shop a:active,
.wishlist_table .product-add-to-cart a.button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.tribe-events-button:active,
#tribe-events .tribe-events-button:active,
#tribe-bar-form .tribe-bar-submit input:active[type=submit],
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.page .edit-link a.active.post-edit-link,
.error404 .active.go-back,
.active.scrollup,
.comment-form .form-submit input.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.elementor-widget-opal-single-product .active.button,
.wc-proceed-to-checkout .active.button,
.woocommerce-cart .return-to-shop a.active,
.wishlist_table .product-add-to-cart a.active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.active.tribe-events-button,
#tribe-events .active.tribe-events-button,
#tribe-bar-form .tribe-bar-submit input.active[type=submit],
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.page .edit-link .show > a.dropdown-toggle.post-edit-link,
.error404 .show > .dropdown-toggle.go-back,
.show > .dropdown-toggle.scrollup,
.comment-form .form-submit .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.elementor-widget-opal-single-product .show > .dropdown-toggle.button,
.wc-proceed-to-checkout .show > .dropdown-toggle.button,
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.wishlist_table .product-add-to-cart .show > a.dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.show > .dropdown-toggle.tribe-events-button,
#tribe-events .show > .dropdown-toggle.tribe-events-button,
#tribe-bar-form .tribe-bar-submit .show > input.dropdown-toggle[type=submit],
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $border_radius, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.elementor-element .elementor-button-secondary .elementor-button {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    border-radius: {$border_radius}px;
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
.button-default,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.page .edit-link a.post-edit-link,
.error404 .go-back,
.scrollup,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.elementor-widget-opal-single-product .button,
.wc-proceed-to-checkout .button,
.woocommerce-cart .return-to-shop a,
.wishlist_table .product-add-to-cart a.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.tribe-events-button,
#tribe-events .tribe-events-button,
#tribe-bar-form .tribe-bar-submit input[type=submit],
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.button-outline-primary,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.button-dark,
.more-link,
.elementor-element .elementor-button-dark .elementor-button,
.elementor-wpcf7-button-dark input[type="button"][type="submit"],
.elementor-wpcf7-button-dark input[type="submit"],
.elementor-wpcf7-button-dark button[type="submit"],
.mailchimp-button-dark button,
table.cart:not(.wishlist_table) td.actions button[type="submit"],
.single-tribe_events .tribe-events-button.tribe-events-ical,
.single-tribe_events #tribe-events .tribe-events-button.tribe-events-ical,
h1,
h2,
h3,
h4,
h5,
h6,
.h1,
.h2,
.h3,
.custom-title,
.entry-header .entry-title,
.related-posts .related-heading,
.comments-title,
.comment-respond .comment-reply-title,
.h4,
.cat-tags-links .tags-heading,
.column-item .entry-title,
.woocommerce-MyAccount-content h2,
.h5,
h2.widget-title,
h2.widgettitle,
.h6,
.widget_rss li .rsswidget,
blockquote,
.main-navigation,
.mp-menu,
.entry-header .entry-date a,
.entry-meta,
.single .navigation .nav-link,
.author-wrapper .author-name,
.error404 .error-404 .error-title,
.error404 .error-404-bkg,
.error404 .error-404-subtitle h2,
.error404 .return-home,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.comment-reply-link,
.widget_recent_entries,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-element .elementor-button,
.contactform-content .form-title,
.tribe-events-inner .tribe-events-event-meta,
.start-time .countdown-times > div,
.elementor-widget-heading .elementor-heading-title,
.elementor-widget-heading .sub-title,
.mc4wp-form-fields button,
.elementor-widget-opal-nav-menu,
.elementor-widget-opal-product-categories .cats-total,
.elementor-widget-opal-product-categories .cats-title a,
.scroll-timeline-nav ul li,
.elementor-widget-tabs .elementor-tab-title,
.single-product div.product .summary .price,
.woocommerce-tabs ul.tabs li a,
.single-product .single_add_to_cart_button,
.single-product .single_add_to_cart_button.disabled[type="submit"],
.product_list_widget .product-price,
.woocommerce-product-list .product-price,
.osf-product-deal .woocommerce-product-list .opal-countdown,
.product-style-1 li.product .price,
ul.tribe-events-sub-nav a,
.tribe-events-back a,
.tribe-events-list-widget .tribe-events-widget-link a,
.tribe-events-adv-list-widget .tribe-events-widget-link a,
.tribe-events-list .tribe-events-loop .tribe-events-event-meta,
.entry-content .tribe-events-month .tribe-events-calendar thead th,
.tribe-events-calendar div[id*='tribe-events-daynum-'],
.tribe-events-calendar div[id*='tribe-events-daynum-'] a,
.tribe-events-calendar td.tribe-events-past div[id*='tribe-events-daynum-'],
.tribe-events-calendar td.tribe-events-past div[id*='tribe-events-daynum-'] > a,
.tribe-events-tooltip .tribe-event-duration,
#tribe-bar-form label {
    {$heading_css}
}


CSS;
    return $cssCode;
}
